<a href="https://colab.research.google.com/github/JuanJoe-18/Aplicadas-II/blob/main/Cuaderno13ViernesMayo9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Ejemplo 1.**

$$ f(x,y) = \ln{(y^2-x^2)} $$

no es derivable en $(2,1)$

**Ejemplo 2.**

$$ f(x,y) = \sqrt{x^2+y^2} $$



In [ ]:
import numpy as np

def f(x,y):
  return((x**2+y**2)**(0.5))

n=np.arange(1,50)
h=1/n
z=(f(0,0+h)-f(0,0))/h
z

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
n=np.arange(1,200)
h=1/n
z=(f(0,0+h)-f(0,0))/h
z[-10:]

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
n=np.arange(1,2000)
h=1/n
z=(f(0,0+h)-f(0,0))/h
z[-10:]

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
n=np.arange(1,200)
h=-1/n
z=(f(0,0+h)-f(0,0))/h
z[-10:]

array([-1., -1., -1., -1., -1., -1., -1., -1., -1., -1.])

Con lo anterior concluimos que

$$ \lim_{h \to 0^+} \dfrac{f(0,0+h)-f(0,0)}{h} = 1 $$

y

$$ \lim_{h \to 0^-} \dfrac{f(0,0+h)-f(0,0)}{h} = -1 $$

los límites laterales encontrados son diferentes, por lo tanto $f_y(0,0)$ no existe.



**Ejemplo 3.**

$$ f(x,y) = |x| $$

Determine si existen las siguientes derivadas parciales, si existen calculelas

1. $f_x(0,0)$
2. $f_x(0,1)$
3. $f_x(1,0)$
4. $f_y(0,0)$
5. $f_y(0,1)$
6. $f_y(1,0)$


In [ ]:
def f(x,y):
  return(abs(x))

n=np.arange(1,50)
h=1/n
z=(f(0+h,0)-f(0,0))/h
z

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
n=np.arange(1,50)
h=-1/n
z=(f(0+h,0)-f(0,0))/h
z

array([-1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1.,
       -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1.,
       -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1.,
       -1., -1., -1., -1., -1., -1., -1., -1., -1., -1.])

Entonces podemos concluir que $f_x(0,0)$ no existe debido a que los límites laterales son diferentes

**Ejemplo 5**

Considere la función $$ f(x,y) = 4-8x^2 - 2y^2  $$

Encuentre la linealización de $f$ en el punto (1,2). Grafique la función, el punto y la linealización.

**Solución**

$$f_x(x,y) = -16x, \ \ \ \ f_x(1,2) = -16$$

$$ f_y(x,y) = -4y, \ \ \ \ f_y(1,2) = -8 $$

Con esto tenemos

$$ L(x,y) = f(1,2) + f_x(1,2)(x-1) + f_y(1,2)(y-2) $$

$$ L(x,y) = -12 -16(x-1) -8(y-2) $$